# Generated by Django 5.1.1 on 2024-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsmodel_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('carousel', 'carousel'), ('categorized', 'categorized')], max_length=128)),
                ('news', models.ManyToManyField(related_name='collection', to='news.newsmodel')),
            ],
            options={
                'verbose_name': 'News Collection',
                'verbose_name_plural': 'News Collections',
            },
        ),
    ]
